version: "3.7"
services:
  app:
    build:
      context: ./environment/app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  db:
    build:
      context: ./environment/db
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
