# Ubuntu version
FROM ubuntu:18.04

# Set working directory of client machine
WORKDIR /home/ubuntu

# Apt-update and upgrade
RUN apt-get update && apt-get install -y gnupg2
RUN apt-get upgrade -y

# ubuntu key and source add
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv D68FA50FEA312927
RUN echo "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-3.2.list

# Apt-update and upgrade
RUN apt-get update -y
RUN apt-get upgrade

# Install Mongodb
RUN apt-get install -y mongodb-org=3.2.20 mongodb-org-server=3.2.20 mongodb-org-shell=3.2.20 mongodb-org-mongos=3.2.20 mongodb-org-tools=3.2.20

# Inform Docker that the container is listening on the specified port at runtime.
EXPOSE 27017

# Creating another partition of filesystem
VOLUME /data/db

# Set working directory of client machine
WORKDIR /data

# Run the specified command within the container
CMD [ "mongod", "--smallfiles"]
#CMD [ "mongod", "start" ]
